### ISSUE TITLE
Incomplete import of a channel

### ISSUE THREAD

**Issue by tobihein** [eclipse/packagedrone#60] opened 2016-05-20 11:00 UTC
We use Package Drone 0.13.0.20160205-1310

We want to copy the content of a channel to another channel with a different name.

Therefore we exported the source-channel (see attachement (1)) and tried to import it. We expect 49 artifacts. But after the import the target-channel is not complete. There are artifacts missing. Which artifacts are missing changes with every import. (see screenshot (2))

(1) [export-channel-activiti.zip](https://github.com/eclipse/packagedrone/files/274340/export-channel-activiti.zip)

(2) [screenshot_channels](https://cloud.githubusercontent.com/assets/19488577/15425688/4ea13888-1e8a-11e6-957f-f2b069a11a5a.jpg)

**Comment by ctron** [comment] 2016-05-20 11:02
I will have a look at it.

**Comment by ctron** [comment] 2016-05-20 11:05
I actually do get a `NullPointerException`, do you get any exception?

**Comment by ctron** [comment] 2016-05-20 11:11
Can you test and see if "Maintenance" -> "Refresh aspects" in the channel view brings back the missing artifacts?

**Comment by tobihein** [comment] 2016-05-20 11:37
Thanks for your answer. Refreshing the aspects seems to "repair" everything. That means, that everything is ok after the refresh? Or is there a possible problem for the future when consuming from the new channel?

I don't get a nullpointer-exception in the log-file. But this can also be because of my logback.xml

`<?xml version="1.0" encoding="UTF-8"?>

<configuration scan="true" scanPeriod="30 seconds">

	<contextListener class="ch.qos.logback.classic.jul.LevelChangePropagator">
		<resetJUL>true</resetJUL>
	</contextListener>

        <appender name="LOG_FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
                <file>log/pdrone.log</file>
                <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                        
                        <fileNamePattern>log/pdrone_%d{yyyy-MM-dd}.log</fileNamePattern>
                </rollingPolicy>
                <encoder>
			<pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
                </encoder>
        </appender>

	<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
		</encoder>
	</appender>
	
    <logger name="org.eclipse.packagedrone" level="INFO"/>
                  
	<root level="info">
		<appender-ref ref="STDOUT" />
		<appender-ref ref="LOG_FILE" />
	</root>
</configuration>
`

**Comment by ctron** [comment] 2016-05-20 11:57
Everything should be fine afterwards. The issue is that adding multiple aspects in one call causes problems.

**Comment by ctron** [comment] 2016-05-20 13:32
This will be fixed in the final release.

**Comment by ctron** [comment] 2016-05-20 13:33
Thanks for reporting!

**Closed by ctron** 2016-05-20 13:32 UTC
Labels: bug

**Comment by tobihein** [comment] 2016-05-20 13:40
Thanks for your support. You do a great job.
